# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adrian’s Blog
author: Adrian Lafond
description: Analog observations rendered digitally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adrianlafond.github.io" # the base hostname & protocol for your site

# @see http://wbwip.com/wbw/emailencoder.html
email: "&#109;&#097;&#105;&#108;&#064;&#097;&#100;&#114;&#105;&#097;&#110;&#108;&#097;&#102;&#111;&#110;&#100;&#046;&#099;&#111;&#109;"

social:
  instagram:  adrianlafond
  twitter:    adrianlafond
  github:     adrianlafond

# Build settings
markdown: kramdown
# theme: minima

sass:
  style:            :expanded

gems:
  - jekyll-feed
